# Generated by Django 6.0.2 on 2026-02-07 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviewHelperApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionbank',
            old_name='user',
            new_name='creator',
        ),
    ]
